app/urls.py
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    path('', views.index, name='index'), 
    path('peliculas/',views.peliculas,name='peliculas'), #el primero es para ver como se ve la url ,el segundo es como la variable
    path('registro/',views.form_registro,name='form_registro'),
    path('registro_post/',views.post_registro,name='post_registro'),
    path('bienvenida/',views.bienvenida,name='bienvenida'),
    path('login/',views.form_login,name='form_login'),
    path('login_post/',views.post_login,name='post_login'),
    path('logout/',views.post_logout,name='post_logout'),
    path('categorias/',views.categorias,name='categorias'),
    path('categorias/crear',views.form_crear_categoria,name='form_crear_categoria'),
    path('peliculas/<int:id>/', views.pelicula,name='pelicula'),
     path('peliculas/crear',views.form_crear_pelicula,name='form_crear_pelicula'),
    path('acercade', views.acercade,name='acercade'),
    path('categorias/crear_post',views.post_crear_categoria,name='post_crear_categoria'),
    path('peliculas/crear_post',views.post_crear_pelicula,name='post_crear_pelicula'),
    
]

blockbuster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
     path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

# Create your models here.

# null = true acepta campos nulos
# pelicula tiene una llave foranea(Relacion de uno a muchos) , y sea crea una bidireccion de uno a muchos

class Categoria(models.Model):
    nombre=models.CharField(max_length=100)
    descripcion=models.TextField()

    def __str__(self): #Representacion en texto de un objeto
        return self.nombre

    class Meta():
        app_label: 'app'

class Pelicula(models.Model):
    titulo=models.CharField(max_length=200)
    year = models.IntegerField(null=True)
    sinopsis=models.TextField()
    actores=models.TextField(null=True)
    categoria=models.ForeignKey(
        Categoria,
        related_name='peliculas',
        on_delete=models.PROTECT
    )

    def __str__(self):
        return self.titulo
    
    class Meta:
        app_label: 'app'
    
     

app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .models import Categoria, Pelicula
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
""" lista=["Avatar","Shrek","Star","Hello","Gao"]
lista2=[
    {"id":0,"nombre":"Holaa1","year":1998},
    {"id":1,"nombre":"Holaa2","year":1998},
    {"id":2,"nombre":"Holaa3","year":2000},


] """

def index(request):
    return render(request,'app/index.html')

@login_required 
def peliculas(request):
    
    """ if not request.user.is_authenticated:
        return render(request,'app/403.html') """

    # Obtiene las peliculas
    listap = Pelicula.objects.all().order_by('year')
    # Crea el contexto
    contexto = {
        'peliculas': listap
    }

    return render(request, 'app/peliculas.html', contexto)
    
@login_required 
def pelicula(request,id):
    """ obj_pelicula = get_object_or_404(Pelicula,pk=id) """
    """ print(id) """ #Probar en consola
    obj_pelicula = Pelicula.objects.get(id=id)
    contexto={
        'pelicula':obj_pelicula
    }

    """ contexto={}
    
    if id < len(lista):
        contexto['pelicula']=lista[id] """

    return render(request,'app/pelicula.html',contexto)

@login_required 
def categorias(request):
    lista = Categoria.objects.all()
    contexto = {
        'categorias':lista
    }


    return render(request,'app/categorias.html',contexto)

@login_required 
def acercade(request):
    return render(request,'app/acercade.html')

@login_required 
def form_crear_categoria(request):
    return render(request,'app/formCrearCategoria.html')

@login_required 
def post_crear_categoria(request):
    #Leyendo datos
    nombre =request.POST['nombre']

    cat = Categoria(nombre=nombre)

    cat.save()

    return redirect('app:categorias')

@login_required 
def form_crear_pelicula(request):
    lista_categorias = Categoria.objects.all().order_by('nombre')
    contexto = {
        'categorias':lista_categorias
    }
    return render(request,'app/formCrearPelicula.html',contexto)

@login_required 
def post_crear_pelicula(request):

    titulo = request.POST['titulo']
    year = request.POST['year']
    sinopsis = request.POST['sinopsis']
    actores = request.POST['actores']
    id_categoria = int(request.POST['categoria'])

    #Obtiene la categoria

    categoria = Categoria.objects.get(pk=id_categoria)

    nueva_pel = Pelicula()
    nueva_pel.titulo=titulo
    nueva_pel.year=year
    nueva_pel.sinopsis=sinopsis
    nueva_pel.actores=actores
    nueva_pel.categoria=categoria

    nueva_pel.save()
    return redirect('app:peliculas')
@login_required 
def post_eliminar_categoria(request):

    borrar = Categoria(nombre='Drama')
    borrar = Categoria.delete()

    return redirect('app:categorias')

def form_registro(request):
    return render(request,'app/registro.html')

def bienvenida(request):
    return render(request,'app/bienvenida.html')

def post_registro(request):
    nombres = request.POST['nombres']
    usuario = request.POST['usuario']
    email = request.POST['email']
    clave = request.POST['clave']
    
    u = User()
    u.first_name=nombres
    u.username=usuario
    u.email=email
    u.set_password(clave)
    u.save()



    """ print(nombres,usuario,email,clave) """
    return redirect('app:bienvenida')


def form_login(request):
    return render(request,'app/login.html')


def post_login(request):
    usuario = request.POST['usuario']
    clave = request.POST['clave']
    u = authenticate(username=usuario,password=clave)
    
    if u is None:
        print('claves incorrectas')
        return HttpResponse("Su usuario o clave es incorrecta")
    else:
        login(request,u)
        return redirect('app:index')

def post_logout(request):
    logout(request)
    return redirect('app:index')

app/templates/app/acercade.html
{% extends 'app/layout.html' %}

{% block contenido  %}

<h1>Una pagina hecha en colombia</h1>


{% endblock  %}

app/templates/app/bienvenida.html
{% extends 'app/layout.html' %}

{% block contenido  %}

<h1>Bienvenido a blockbuster</h1>
<p>ud acabo de crear una cuenta</p>

{% endblock  %}

app/templates/app/categorias.html
{%extends 'app/layout.html'%}
{% block contenido %}

<a href="{% url 'app:form_crear_categoria' %}">Crear Categoria</a>
<ul>

    {% for c in categorias %}
        <li>{{c.nombre}}</li>
    {% endfor%}
    


</ul>
{% endblock %}
{%block titulo%}
Categorias:
{%endblock%}

app/templates/app/formCrearCategoria.html
{%extends 'app/layout.html'%}

{% block titulo%}
Crear categoria
{%endblock%}

{% block contenido%}
<form action="{% url 'app:post_crear_categoria'%}" method="POST">
{% csrf_token%}
<label for="nombre">Nombre de categoria:</label>
<input type="text" name="nombre">
<button type="submit">Crear</button>


</form>


{%endblock%}

app/templates/app/formCrearPelicula.html
{%extends 'app/layout.html'%}

{% block titulo%}
Crear Pelicula
{%endblock%}

{% block contenido%}
<form action="{%url 'app:post_crear_pelicula'%}" method="POST">
    {% csrf_token%}
    
<label for="titulo">Titulo:</label>
<input type="text" name="titulo"> 
<br>
<label for="year">Año:</label>
<input type="number" name="year"> 
<br>
<label for="sinopsis">Sinopsis:</label>
<input type="text" name="sinopsis"> 
<br>
<label for="actores">Actores:</label>
<input type="text" name="actores"> 
<br>
<label for="categoria">Categoria</label>
<select name="categoria">

{% for c in categorias%}

<option value="{{c.id}}">{{c.nombre}}</option>

{% endfor %}

</select>
<br>
<button type="submit" >Crear</button>
</form>
{%endblock%}

app/templates/app/index.html
{%extends 'app/layout.html'%}
{% block contenido %}
<p>Este es el contenido de la pagina inicial</p>

{% if request.user.is_authenticated %}

<p>Hola {{request.user.first_name}} {{request.user.id}} </p>
{% else %}

<p>Si deseas ingresas haz click  <a href="{% url 'app:form_login' %}">Aqui</a> </p>
{%endif%}
{% endblock %}

app/templates/app/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blockbuster</title>
    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
</head>
<body>


<div class="contenedor">

<div class="header" >
    <h1>
    <img src="{% static 'app/img/logo_bb.png' %}"  class="logo" alt="BB">
    BLOCKBUSTER-<small>{%block titulo%}El mejor sitio{%endblock%}</small> </h1>
</div>
<div class="navegacion" >

    {% if request.user.is_authenticated %}
    <a href="{% url 'app:post_logout' %}">Salir</a>
    <br>
    <a href="{% url 'app:index' %}">inicio</a>
     <br>
    <a href="{% url 'app:peliculas' %}">peliculas</a>
    <br>
    <a href="{% url 'app:categorias' %}">categorias</a>
    <br>
    <a href="{% url 'app:acercade' %}">Nosotros</a>
    {% else %}
    <a href="{% url 'app:form_login' %}">Iniciar Sesion</a>
    <br>
    <a href="{% url 'app:form_registro' %}">Registro</a>
    <br>
    {%endif%}
    
   
    
</div>
<div class="contenido" >
    {% block contenido%}
    {% endblock %}
</div>
<div class="footer" >

    <span>Derechos reservados</span>

</div> 

</div>

    <script src="{% static 'app/js/index.js' %}"></script>
</body>

</html>

app/templates/app/login.html
{% extends 'app/layout.html' %}

{% block titulo  %}

Ingreso
{% endblock  %}

{% block contenido  %}

<h1>Ingreso a block</h1>


<form action="{% url 'app:post_login' %}" method="POST">
    {% csrf_token%}
<label for="usuario">Usuario</label>
<input type="text" name="usuario" >
<br>
<label for="password">Contraseña</label>
<input type="password" name="clave" >
<br>
<button type="submit" >Ingresar</button>

</form>

{% endblock  %}

app/templates/app/pelicula.html
{% extends 'app/layout.html' %}

{% block contenido %} 
{% if pelicula %}
<h1>{{ pelicula.titulo }}</h1> <!-- Toma variable -->
<h3>Año</h3>
<p>{{ pelicula.year }}</p>

{% if pelicula.actores %} <!-- Solo aparece si hay un valor -->
<h3>Actores</h3>
<p>{{ pelicula.actores }}</p>
{% endif %}

<h3>Sinopsis</h3>
<p>{{ pelicula.sinopsis }}</p>
<h3>Categorias</h3>
<p>{{ pelicula.categoria }}</p>
{% else %}
<h1 style="color: red">La película solicitada no existe!</h1>
{% endif %}



{% endblock %}

app/templates/app/peliculas.html
{% extends 'app/layout.html' %}

{% block titulo %}
Películas
{% endblock %}

{% block contenido %}
<a href="{% url 'app:form_crear_pelicula'%}">Crear pelicula</a>
<table border="1" width="100%">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Año</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for p in peliculas %}
        <tr>
            <td>{{ p.titulo }}</td>
            <td>{{ p.year }}</td>
            
            <td>
                <a href="{% url 'app:pelicula' p.id %}">Ver</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

<!-- div class="footer" >
        
            <span>Derechos reservados    {{year}} {{tienda}}</span>
           
   
        
        </div> 
        {% comment %}
        <ul>
       <li>Avatar</li>
       <li>Hola</li>
       <li>Av</li>
       </ul>
       {% endcomment %} -->

app/templates/app/registro.html
{% extends 'app/layout.html' %}

{% block titulo  %}

Registro
{% endblock  %}

{% block contenido  %}

<h1>Datos del usuario</h1>

<form action="{% url 'app:post_registro' %}" method="POST">
    {% csrf_token%}
<label for="nombres">Nombres</label>
<input type="text" name="nombres" >
<br>
<label for="username">Usuario</label>
<input type="text" name="usuario" >
<br>
<label for="email">Correo</label>
<input type="text" name="email" >
<br>
<label for="password">Contraseña</label>
<input type="password" name="clave" >
<br>
<button type="submit" >Crear Cuenta</button>

</form>

{% endblock  %}